### ISSUE TITLE
Escala de log em 2.16

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/licitacoes-pb#10]
No eixo x com certeza. Testem também no eixo y. Vai facilitar muito a visualização.

**Comment by JsLucasSf** [comment]
## Gráfico com eixo x e y em escala de log

![image](https://cloud.githubusercontent.com/assets/6462790/24798965/2c4576cc-1b6f-11e7-8166-71ad5962df22.png)

## Somente x

![image](https://cloud.githubusercontent.com/assets/6462790/24799441/788144ec-1b71-11e7-9a91-573592094f7f.png)

## Original

![image](https://cloud.githubusercontent.com/assets/6462790/24799488/b63e7d86-1b71-11e7-88e7-45c8423b3640.png)

**Comment by JsLucasSf** [comment]
@nazareno Qual a melhor visualização?

**Comment by nazareno** [comment]
Eu prefiro com log. E vocês?
Para o eixo y podíamos tentar o log das propostas+1.
Em sex, 7 de abr de 2017 às 09:11, Js Lucas <notifications@github.com>
escreveu:

@nazareno <https://github.com/nazareno> Qual a melhor visualização?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/analytics-ufcg/licitacoes-pb/issues/10#issuecomment-292520255>,
or mute the thread

**Comment by nazareno** [comment]
Essa issue continua valendo para o novo relatório. Eu prefiro com log no eixo X. Dado que não parece haver relação linear, talvez seja melhor calcular a correlação com o método de kendall.
