### ISSUE TITLE
Temos "realinhamento de preços" nas licitações de merenda?

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/licitacoes-pb#23]
Segundo [esse jornalista](https://www.clickpb.com.br/colunistas/clilsoncol/depois-da-lagosta-haja-charque-frango-e-paleta-197607.html), em uma licitação de alimento para a granja do governador: 

> no meio do caminho (60 dias após a licitação) a "Fonseca Pires" não ganhasse um realinhamento de preços. Quer um exemplo? Item 1 – 15.000 kg de carne bovina paleta sem ossos para as unidades prisionais de Rio Tinto. O pessoal da Central de Compras do Estado (órgão sério criado por Cássio) fez uma pesquisa de mercado e encontrou a mesma “paleta” como menor preço no mercado custando R$ 13,00 (treze reais). A “Fonseca Pires” disse que forneceria a carne na porta do presídio por R$ 7,02 kg e ganhou neste item R$ 105.300,00 para fornecer 15.000 kg. Dois a meses após a  licitação ganhou o tal “realinhamento de preço” de 63,93% e passou a fornecer por R$ 11,59cada kg de paleta bovina. Ou seja, neste item o que totalizava R$ 153.300,00, passou a custar 173.850,00, ou seja, um “migué” na concorrência e sobrepreço de 68.550,00 somente neste item.

Temos realinhamentos como esses nos dados de merenda? Há grandes discrepâncias entre o valor licitado e o valor liquidado nos pagamentos depois? 

E existe em algum lugar essa figura oficial chamada _realinhamento de preço_?

**Comment by JsLucasSf** [comment]
O artigo 40, inciso XI (lei 8666/93) aborda um pouco sobre o que vem a se conhecer como realinhamento de preços

"XI - critério de reajuste, que deverá retratar a variação efetiva do custo de produção, admitida a adoção de índices específicos ou setoriais, desde a data prevista para apresentação da proposta ou do orçamento a que essa proposta se referir até a data do adimplemento de cada parcela;"

Ou seja, é de responsabilidade do edital especificar os termos para o realinhamento.

Outra coisa, é que para futuras referências, aprendi que realinhamentos se fazem na forma de aditivos! explorando esta tabela, encontramos várias observações que possuem como motivo, o realinhamento de preços =)

**Comment by nazareno** [comment]
Legal!
De qual tabela você fala?
Em seg, 10 de abr de 2017 às 11:05, Js Lucas <notifications@github.com>
escreveu:

**Comment by JsLucasSf** [comment]
"Aditivos" mesmo. Tem campo lá pra o motivo do aditivo, e neste campo geralmente tem "realinhamento de preços" na descrição.
