### ISSUE TITLE
Quão frequente é o barato que sai caro?

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/licitacoes-pb#25]
Considerando os "realinhamento de preços" (e supondo que entendemos eles), quão frequente é o caso em que o total pago (liquidado) em uma licitação (de merenda, por enquanto) é bem maior que o lance dado pelo fornecedor _e bem maior que os demais lances dos outros fornecedores que perderam a licitação_?

Minha ideia é criarmos um label para licitações nessa situação. Esse é um indício de que o processo licitatório foi ineficiente: ganhou alguém com um preço que depois não foi praticado.

**Comment by talitalobo** [comment]
Feito.
