### ISSUE TITLE
Melhorar o CSS da página inicial

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/licitacoes-pb#29]
Considerando o design atual: 

- O título da página está repetido
- O subtítulo não está adicionando informação
- Falta uma figura de fundo para a barra do título
- O primeiro título dentro do post está maior que o título do post na página inicial
- Que tal termos uma figura por post? 

![image](https://cloud.githubusercontent.com/assets/1053850/25345943/a04d0a32-28ec-11e7-91ac-9e5ec9723c2d.png)

**Comment by JCNSilva** [comment]
Pontos 1,2 e 4 corrigidos.
@nazareno, eu poderia fechar esse bug e criar dois outros com os pontos que ainda não foram verificados?

**Comment by nazareno** [comment]
Sim!
