### ISSUE TITLE
Checar/melhorar filtragem de licitações que são de merendas

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/licitacoes-pb#34]
Nosso método atual com regex é bom? É melhor ou pior que usar função/subfunção orçamentária para decidir? Avaliar e escolher um método. E documentar em um post como fazemos isso, e fatorar no código a forma de fazer.

**Comment by nazareno** [comment]
Inclusive, o filtro precisa ser o mesmo no código inteiro!

**Comment by nazareno** [comment]
@vctandrade : compila um exemplo de subfunções que aparecem em licitações do nosso filtro atual para perguntarmos a Rossana se há uma lógica.

**Comment by talitalobo** [comment]
Filtro refeito.
