### ISSUE TITLE
Em "Distribuição geográfica dos licitantes de merenda por grupo" conferir que isso é verdade

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/licitacoes-pb#37]
Vento todos os grupos, é difícil avaliar se os licitantes de cada grupo não estão concentrados em diferentes partes do estado. Precisamos conferir com um plot que permita isso. Sugiro um plot do estado da PB por grupo de licitantes.

**Comment by gileadekelvin** [comment]
Atualmente no relatório de distribuição geográfica não temos mais a visualização da localização dos fornecedores por grupo (colorindo por grupo).
