### ISSUE TITLE
Qual a história por trás dos municípios que mais/menos gastaram por aluno em 2015?

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/licitacoes-pb#38]
No post do gasto por aluno, dá para dizer algo sobre o que os municípios que mais gastaram tem de particular na forma de gastar? No número de alunos? Nas descrições das licitações que foram feitas? E os que menos gastaram? Precisamos tentar investigar e contar a história por trás dos números da visão geral.

**Comment by nazareno** [comment]
@gileadekelvin : escolhe uma cidade e conta a lista das licitações, número de escolas e etc.

**Comment by gileadekelvin** [comment]
@nazareno @talitalobo Contando a história de Boa Ventura, apresentei alguns dados escolares como o número de escolas, docentes e matrículas, mas também listei a **única** licitação realizada pelo município em 2015 que foi capturada pelo filtro (usando a palavra merenda). Achei estranho e fui ler todas as licitações em 2015 realizadas pelo município e cheguei a uma lista de possíveis outras licitações que poderiam ser de merenda. 
![tabela](https://cloud.githubusercontent.com/assets/10724115/26167572/78a2b512-3b0d-11e7-8e8e-1b575ee6e8ec.png)

A primeira licitação da tabela foi a capturada pelo filtro, as duas abaixo foram resultados da minha pesquisa. As descrições são genéricas mas possivelmente são de merenda. Descrições genéricas como "aquisição de gêneros alimentícios para diversas secretarias do município" são encontradas com uma certa frequência nos dados. 

Assim como Boa Ventura, realizei o mesmo procedimento com Rio Tinto (ambas estão na lista das que menos gastam por aluno) e encontrei outras licitações que possivelmente são de merenda mas não foram capturadas pelo filtro. Para algumas outras cidades (Santa Helena e Santa Inês) que realizaram apenas uma licitação no ano (de merenda) o filtro conseguiu capturar e não encontrei outras licitações.

No relatório considerei que a análise de gasto por aluno faz sentido, no entanto algumas limitações no filtro fazem com que algumas cidades não tenham todas suas licitações de merenda capturadas, o que é ruim para a análise. A pesquisa foi satisfatória para responder a pergunta? (o relatório está [aqui](https://github.com/analytics-ufcg/licitacoes-pb/blob/custo-por-aluno/analises/merenda/custo-por-aluno/2017-04-22-custo-por-aluno.html))

**Comment by nazareno** [comment]
Oi Gileade. Acho que foi o melhor trabalho que dá para fazer agora. Deixa
um bug registrado aqui no github nos lembrando que o filtro que alimentou a
análise tem bugs.

**Comment by nazareno** [comment]
E você podia colocar no site o post, por favor?

**Comment by gileadekelvin** [comment]
Acabei de criar um bug aqui. Iremos colocar no site amanhã assim que pudermos, junto com o refatoramento do código de outros relatórios.
