### ISSUE TITLE
Há um padrão nas licitações dos municípios que mais licitaram?

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/licitacoes-pb#4]
Alguns municípios na pergunta 2.2 do relatório tem 40 licitações. Essas licitações deram todas certo? Foram todas canceladas? Os valores são muito diferentes dos de outras cidades? O que aconteceu?

**Comment by JCNSilva** [comment]
Ao retirar o ano de 2010 da análise, não há mais nenhum dos municípios com 40 licitações. O máximo passou a ser 21. Essa issue continua válida mesmo com a redução no total de licitações?

![Número de Licitações por Município](https://cloud.githubusercontent.com/assets/9270386/25179788/be46de28-24e1-11e7-80b5-ca158629c45f.png)

**Comment by nazareno** [comment]
Como é um plot com o número de licitações por município, com todos os municípios ordenados do que fez mais pro que fez menos licitações?
