### ISSUE TITLE
nomes dos grupos no grafico 2

### ISSUE THREAD

**Issue by raquelvl** [analytics-ufcg/licitacoes-pb#42]
Vocês já explicaram que em outro relatório tem a explicação dos grupos. Imagino que vcs tem nomes representativos para esses  grupos e seria muito interessante se nesse grafico a gente pudesse pelo menos ver esses nomes. Isso é no relatório localizacao-fornecedores.html.

**Comment by hugogbs** [comment]
Na nova versão do relatório não existe mais a visualização em grupos.
