### ISSUE TITLE
será que conseguimos os dados de 2016?

### ISSUE THREAD

**Issue by raquelvl** [analytics-ufcg/licitacoes-pb#43]
@nazareno @talitalobo será que teriamos acesso aos dados de licitaçÕes de 2016? ja estamos quase na metade de 2017... esses dados já devem existir em algum lugar. 

[não sei colocar labels :(]

**Comment by talitalobo** [comment]
Sim, @raquelvl . Acredito que Octavio vai nos atualizar quanto a isso mais perto do Hackfest que vai rolar em Junho. Acho que Nazareno tinha comentado sobre isso mas acho que tu não tava na hora.
