### ISSUE TITLE
A modalidade 'chamada pública' é uma garantia de contratação ou os fornecedores concorrerão entre si?

### ISSUE THREAD

**Issue by talitalobo** [analytics-ufcg/licitacoes-pb#59]

**Comment by JCNSilva** [comment]
@talitalobo Pesquisei pelas propostas realizadas para licitações da modalidade chamada pública em nossos dados e há propostas vencedoras e perdedoras, indicando que há concorrência.
Na foto abaixo, os níveis de st_proposta são:
- 1: Proposta vencedora
- 2: Proposta perdedora

![Foto](https://user-images.githubusercontent.com/9270386/28182800-a2fa6956-67e3-11e7-910f-31dab057c4a1.png)

**Comment by JCNSilva** [comment]
Apenas complementando, há uma prioridade para a seleção das propostas vencedoras nessa modalidade que leva em consideração a que grupo pertence o agricultor (quilombola, indígena, informal ou formal, por exemplo), quando a mesma é aplicada para obtenção de produtos da agricultura familiar. 
Mais detalhes sobre essa prioridade podem ser encontrados nesse [link](http://www.mda.gov.br/sitemda/secretaria/saf-ali/como-funciona-compra-e-venda-de-produtos-da-agricultura-familiar)
