### ISSUE TITLE
Relatório de agrupamento

### ISSUE THREAD

**Issue by talitalobo** [analytics-ufcg/licitacoes-pb#61]
Testar com 10 grupos e comparar os resultados

**Comment by gileadekelvin** [comment]
Com base na visualização abaixo:
![agrupamento_licitantes](https://user-images.githubusercontent.com/10724115/28211455-201a471e-6873-11e7-8891-7f796e8e71b7.png)
Foi decidido na reunião que iríamos testar com 10 e comparar com o de 6 grupos.

Com 6 grupos temos:
![Agrupamento - 6 grupos](https://user-images.githubusercontent.com/10724115/28211399-d427a91e-6872-11e7-920f-87d6762b215d.png)
Com 10 grupos temos:
![Agrupamento - 10 grupos](https://user-images.githubusercontent.com/10724115/28211467-3285e5fc-6873-11e7-978e-f2122a19d563.png)

Observamos que os grupos são mais definidos na divisão em 10. Não conseguimos plotar a silhueta pois há muitas observações e o R não consegue alocar o vector.

**Comment by gileadekelvin** [comment]
Comparamos e decidimos pelo agrupamento com 6 grupos.
