### ISSUE TITLE
Folha de pagamento entra nos dados que analisamos?

### ISSUE THREAD

**Issue by talitalobo** [analytics-ufcg/licitacoes-pb#77]

**Comment by hugogbs** [comment]
Em alguns relatórios sim, em outros não.
Entra em:
- Descrição dos compradores e fornecedores de merenda
- Descrição dos fornecedores de merenda
- Realinhamento de Preços
Não está em:
- Classificação dos licitantes de merenda
- Distribuição Geográfica dos Licitantes
